/**
 * build.mjs — 零依赖打包脚本（无需 npm 安装任何包）。
 *
 * 作用：把使用 ES Modules 的源码打包成「即开即玩」的产物：
 *   1) dist/neon-drift.html —— 完全自包含的单文件（CSS + JS 全内联），
 *      可直接双击用浏览器打开（file:// 协议），也便于分发到手机。
 *   2) dist/index.html + dist/game.js —— 同样内容的分离版（game.js 为普通脚本，
 *      file:// 下同样可双击 index.html 运行）。
 *
 * 原理：实现一个迷你 CommonJS 风格的模块加载器。把每个源模块包成独立函数作用域，
 * 将 `import { a } from "x"` 转为 `const { a } = require("x")`，
 * 将 `export class/const/function ...` 的 export 前缀剥离并在模块末尾统一挂到 exports。
 * 由此规避全局命名冲突，且无需任何外部打包器。
 *
 * 适用前提（本项目均满足）：仅使用具名 import/export、单行 import、无 default/重命名导入、无模块循环依赖。
 */
import { readFileSync, writeFileSync, mkdirSync, readdirSync, statSync } from "node:fs";
import { dirname, resolve, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = dirname(fileURLToPath(import.meta.url));
const JS_DIR = join(ROOT, "js");
const ENTRY = join(JS_DIR, "main.js");
const DIST = join(ROOT, "dist");

/** 递归收集 js 目录下所有 .js 文件的绝对路径 */
function collectJsFiles(dir, acc = []) {
  for (const name of readdirSync(dir)) {
    const full = join(dir, name);
    if (statSync(full).isDirectory()) collectJsFiles(full, acc);
    else if (name.endsWith(".js")) acc.push(full);
  }
  return acc;
}

/** 把单个模块源码转换为加载器可注册的函数体 */
function transformModule(absPath) {
  const fileDir = dirname(absPath);
  let src = readFileSync(absPath, "utf8");

  // 1) import { a, b } from "spec"  ->  const { a, b } = require("<absResolved>")
  src = src.replace(
    /import\s*\{([^}]*)\}\s*from\s*["']([^"']+)["'];?/g,
    (_m, names, spec) => {
      const target = resolve(fileDir, spec);
      return `const {${names.trim()}} = require(${JSON.stringify(target)});`;
    }
  );

  // 2) 剥离 export 前缀并收集导出名
  const exportNames = [];
  src = src.replace(
    /^export\s+(class|const|let|var|function)\s+([A-Za-z0-9_$]+)/gm,
    (_m, kind, name) => {
      exportNames.push(name);
      return `${kind} ${name}`;
    }
  );

  const tail = exportNames.length
    ? `\nObject.assign(exports, { ${exportNames.join(", ")} });`
    : "";

  return `__defs[${JSON.stringify(absPath)}] = function (exports, require) {\n${src}${tail}\n};`;
}

function buildBundle() {
  const files = collectJsFiles(JS_DIR);
  const defs = files.map(transformModule).join("\n\n");

  return `/* NEON DRIFT — bundled build (generated by build.mjs, do not edit) */
(function () {
  "use strict";
  var __defs = {};
  var __cache = {};
  function require(key) {
    if (__cache[key]) return __cache[key].exports;
    var module = (__cache[key] = { exports: {} });
    if (!__defs[key]) throw new Error("Module not found: " + key);
    __defs[key](module.exports, require);
    return module.exports;
  }

${defs}

  require(${JSON.stringify(ENTRY)});
})();
`;
}

function main() {
  mkdirSync(DIST, { recursive: true });

  const bundle = buildBundle();
  const css = readFileSync(join(ROOT, "css", "style.css"), "utf8");
  const html = readFileSync(join(ROOT, "index.html"), "utf8");

  // 防止内联脚本意外闭合 </script>（本项目无，仍做防御）
  const safeBundle = bundle.replace(/<\/(script)/gi, "<\\/$1");

  // ---- 自包含单文件：同时输出为 index.html（部署入口/根路径直达）与 neon-drift.html（便于分发）----
  const single = html
    .replace(/<link[^>]*href="\.\/css\/style\.css"[^>]*>/, `<style>\n${css}\n</style>`)
    .replace(
      /<script[^>]*src="\.\/js\/main\.js"[^>]*><\/script>/,
      `<script>\n${safeBundle}\n</script>`
    );
  writeFileSync(join(DIST, "neon-drift.html"), single, "utf8");
  writeFileSync(join(DIST, "index.html"), single, "utf8");

  // ---- 可选分离版（供调试/语法校验）；index.html 不依赖它 ----
  writeFileSync(join(DIST, "game.js"), bundle, "utf8");
  const split = html
    .replace(/<link[^>]*href="\.\/css\/style\.css"[^>]*>/, `<style>\n${css}\n</style>`)
    .replace(
      /<script[^>]*src="\.\/js\/main\.js"[^>]*><\/script>/,
      `<script src="./game.js"></script>`
    );
  writeFileSync(join(DIST, "split.html"), split, "utf8");

  const kb = (s) => (Buffer.byteLength(s, "utf8") / 1024).toFixed(1) + " KB";
  console.log("Build complete:");
  console.log("  dist/index.html        (自包含, 部署入口/根路径直达)  " + kb(single));
  console.log("  dist/neon-drift.html   (自包含, 同上, 便于分发)        " + kb(single));
  console.log("  dist/split.html + game.js  (分离版, 可选)              " + kb(bundle));
}

main();
